// flow-typed signature: 8ff0e4124ea231a8e086cf53c822bea9
// flow-typed version: <<STUB>>/opentracing_v^0.14.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opentracing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "opentracing" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "opentracing/lib/binary_carrier" {
  declare module.exports: any;
}

declare module "opentracing/lib/constants" {
  declare module.exports: any;
}

declare module "opentracing/lib/examples/demo/demo" {
  declare module.exports: any;
}

declare module "opentracing/lib/ext/tags" {
  declare module.exports: any;
}

declare module "opentracing/lib/functions" {
  declare module.exports: any;
}

declare module "opentracing/lib/global_tracer" {
  declare module.exports: any;
}

declare module "opentracing/lib/index" {
  declare module.exports: any;
}

declare module "opentracing/lib/mock_tracer/index" {
  declare module.exports: any;
}

declare module "opentracing/lib/mock_tracer/mock_context" {
  declare module.exports: any;
}

declare module "opentracing/lib/mock_tracer/mock_report" {
  declare module.exports: any;
}

declare module "opentracing/lib/mock_tracer/mock_span" {
  declare module.exports: any;
}

declare module "opentracing/lib/mock_tracer/mock_tracer" {
  declare module.exports: any;
}

declare module "opentracing/lib/noop" {
  declare module.exports: any;
}

declare module "opentracing/lib/reference" {
  declare module.exports: any;
}

declare module "opentracing/lib/span_context" {
  declare module.exports: any;
}

declare module "opentracing/lib/span" {
  declare module.exports: any;
}

declare module "opentracing/lib/test/api_compatibility" {
  declare module.exports: any;
}

declare module "opentracing/lib/test/noop_implementation" {
  declare module.exports: any;
}

declare module "opentracing/lib/test/opentracing_api" {
  declare module.exports: any;
}

declare module "opentracing/lib/test/unittest" {
  declare module.exports: any;
}

declare module "opentracing/lib/tracer" {
  declare module.exports: any;
}

declare module "opentracing/webpack.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "opentracing/lib/binary_carrier.js" {
  declare module.exports: $Exports<"opentracing/lib/binary_carrier">;
}
declare module "opentracing/lib/constants.js" {
  declare module.exports: $Exports<"opentracing/lib/constants">;
}
declare module "opentracing/lib/examples/demo/demo.js" {
  declare module.exports: $Exports<"opentracing/lib/examples/demo/demo">;
}
declare module "opentracing/lib/ext/tags.js" {
  declare module.exports: $Exports<"opentracing/lib/ext/tags">;
}
declare module "opentracing/lib/functions.js" {
  declare module.exports: $Exports<"opentracing/lib/functions">;
}
declare module "opentracing/lib/global_tracer.js" {
  declare module.exports: $Exports<"opentracing/lib/global_tracer">;
}
declare module "opentracing/lib/index.js" {
  declare module.exports: $Exports<"opentracing/lib/index">;
}
declare module "opentracing/lib/mock_tracer/index.js" {
  declare module.exports: $Exports<"opentracing/lib/mock_tracer/index">;
}
declare module "opentracing/lib/mock_tracer/mock_context.js" {
  declare module.exports: $Exports<"opentracing/lib/mock_tracer/mock_context">;
}
declare module "opentracing/lib/mock_tracer/mock_report.js" {
  declare module.exports: $Exports<"opentracing/lib/mock_tracer/mock_report">;
}
declare module "opentracing/lib/mock_tracer/mock_span.js" {
  declare module.exports: $Exports<"opentracing/lib/mock_tracer/mock_span">;
}
declare module "opentracing/lib/mock_tracer/mock_tracer.js" {
  declare module.exports: $Exports<"opentracing/lib/mock_tracer/mock_tracer">;
}
declare module "opentracing/lib/noop.js" {
  declare module.exports: $Exports<"opentracing/lib/noop">;
}
declare module "opentracing/lib/reference.js" {
  declare module.exports: $Exports<"opentracing/lib/reference">;
}
declare module "opentracing/lib/span_context.js" {
  declare module.exports: $Exports<"opentracing/lib/span_context">;
}
declare module "opentracing/lib/span.js" {
  declare module.exports: $Exports<"opentracing/lib/span">;
}
declare module "opentracing/lib/test/api_compatibility.js" {
  declare module.exports: $Exports<"opentracing/lib/test/api_compatibility">;
}
declare module "opentracing/lib/test/noop_implementation.js" {
  declare module.exports: $Exports<"opentracing/lib/test/noop_implementation">;
}
declare module "opentracing/lib/test/opentracing_api.js" {
  declare module.exports: $Exports<"opentracing/lib/test/opentracing_api">;
}
declare module "opentracing/lib/test/unittest.js" {
  declare module.exports: $Exports<"opentracing/lib/test/unittest">;
}
declare module "opentracing/lib/tracer.js" {
  declare module.exports: $Exports<"opentracing/lib/tracer">;
}
declare module "opentracing/webpack.config.js" {
  declare module.exports: $Exports<"opentracing/webpack.config">;
}
