// flow-typed signature: a9cd355516b2d846e0f3f1ade5ffb208
// flow-typed version: <<STUB>>/zipkin-transport-http_v^0.10.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zipkin-transport-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "zipkin-transport-http" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "zipkin-transport-http/lib/HttpLogger" {
  declare module.exports: any;
}

declare module "zipkin-transport-http/lib/index" {
  declare module.exports: any;
}

declare module "zipkin-transport-http/src/HttpLogger" {
  declare module.exports: any;
}

declare module "zipkin-transport-http/src/index" {
  declare module.exports: any;
}

declare module "zipkin-transport-http/test/integrationTest" {
  declare module.exports: any;
}

// Filename aliases
declare module "zipkin-transport-http/lib/HttpLogger.js" {
  declare module.exports: $Exports<"zipkin-transport-http/lib/HttpLogger">;
}
declare module "zipkin-transport-http/lib/index.js" {
  declare module.exports: $Exports<"zipkin-transport-http/lib/index">;
}
declare module "zipkin-transport-http/src/HttpLogger.js" {
  declare module.exports: $Exports<"zipkin-transport-http/src/HttpLogger">;
}
declare module "zipkin-transport-http/src/index.js" {
  declare module.exports: $Exports<"zipkin-transport-http/src/index">;
}
declare module "zipkin-transport-http/test/integrationTest.js" {
  declare module.exports: $Exports<
    "zipkin-transport-http/test/integrationTest"
  >;
}
