// flow-typed signature: 8248532da23bfe33a41b379ebe399d4b
// flow-typed version: <<STUB>>/zipkin_v^0.10.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zipkin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "zipkin" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "zipkin/lib/annotation" {
  declare module.exports: any;
}

declare module "zipkin/lib/batch-recorder" {
  declare module.exports: any;
}

declare module "zipkin/lib/console-recorder" {
  declare module.exports: any;
}

declare module "zipkin/lib/encoder" {
  declare module.exports: any;
}

declare module "zipkin/lib/explicit-context" {
  declare module.exports: any;
}

declare module "zipkin/lib/httpHeaders" {
  declare module.exports: any;
}

declare module "zipkin/lib/index" {
  declare module.exports: any;
}

declare module "zipkin/lib/InetAddress" {
  declare module.exports: any;
}

declare module "zipkin/lib/instrumentation/httpClient" {
  declare module.exports: any;
}

declare module "zipkin/lib/instrumentation/httpServer" {
  declare module.exports: any;
}

declare module "zipkin/lib/instrumentation/index" {
  declare module.exports: any;
}

declare module "zipkin/lib/json-v1" {
  declare module.exports: any;
}

declare module "zipkin/lib/jsonEncoder" {
  declare module.exports: any;
}

declare module "zipkin/lib/model" {
  declare module.exports: any;
}

declare module "zipkin/lib/option" {
  declare module.exports: any;
}

declare module "zipkin/lib/request" {
  declare module.exports: any;
}

declare module "zipkin/lib/time" {
  declare module.exports: any;
}

declare module "zipkin/lib/tracer/index" {
  declare module.exports: any;
}

declare module "zipkin/lib/tracer/noop" {
  declare module.exports: any;
}

declare module "zipkin/lib/tracer/randomTraceId" {
  declare module.exports: any;
}

declare module "zipkin/lib/tracer/record" {
  declare module.exports: any;
}

declare module "zipkin/lib/tracer/sampler" {
  declare module.exports: any;
}

declare module "zipkin/lib/tracer/TraceId" {
  declare module.exports: any;
}

declare module "zipkin/src/annotation" {
  declare module.exports: any;
}

declare module "zipkin/src/batch-recorder" {
  declare module.exports: any;
}

declare module "zipkin/src/console-recorder" {
  declare module.exports: any;
}

declare module "zipkin/src/explicit-context" {
  declare module.exports: any;
}

declare module "zipkin/src/httpHeaders" {
  declare module.exports: any;
}

declare module "zipkin/src/index" {
  declare module.exports: any;
}

declare module "zipkin/src/InetAddress" {
  declare module.exports: any;
}

declare module "zipkin/src/instrumentation/httpClient" {
  declare module.exports: any;
}

declare module "zipkin/src/instrumentation/httpServer" {
  declare module.exports: any;
}

declare module "zipkin/src/instrumentation/index" {
  declare module.exports: any;
}

declare module "zipkin/src/jsonEncoder" {
  declare module.exports: any;
}

declare module "zipkin/src/model" {
  declare module.exports: any;
}

declare module "zipkin/src/option" {
  declare module.exports: any;
}

declare module "zipkin/src/request" {
  declare module.exports: any;
}

declare module "zipkin/src/time" {
  declare module.exports: any;
}

declare module "zipkin/src/tracer/index" {
  declare module.exports: any;
}

declare module "zipkin/src/tracer/noop" {
  declare module.exports: any;
}

declare module "zipkin/src/tracer/randomTraceId" {
  declare module.exports: any;
}

declare module "zipkin/src/tracer/record" {
  declare module.exports: any;
}

declare module "zipkin/src/tracer/sampler" {
  declare module.exports: any;
}

declare module "zipkin/src/tracer/TraceId" {
  declare module.exports: any;
}

declare module "zipkin/test/annotation.test" {
  declare module.exports: any;
}

declare module "zipkin/test/batch-recorder.test" {
  declare module.exports: any;
}

declare module "zipkin/test/explicit-context.test" {
  declare module.exports: any;
}

declare module "zipkin/test/httpClientInstrumentation.test" {
  declare module.exports: any;
}

declare module "zipkin/test/httpServerInstrumentation.test" {
  declare module.exports: any;
}

declare module "zipkin/test/InetAddress.test" {
  declare module.exports: any;
}

declare module "zipkin/test/jsonEncoder.JSON_V1.test" {
  declare module.exports: any;
}

declare module "zipkin/test/jsonEncoder.JSON_V2.test" {
  declare module.exports: any;
}

declare module "zipkin/test/model.test" {
  declare module.exports: any;
}

declare module "zipkin/test/randomTraceId.test" {
  declare module.exports: any;
}

declare module "zipkin/test/request.test" {
  declare module.exports: any;
}

declare module "zipkin/test/sampler.test" {
  declare module.exports: any;
}

declare module "zipkin/test/trace.test" {
  declare module.exports: any;
}

declare module "zipkin/test/TraceId.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "zipkin/lib/annotation.js" {
  declare module.exports: $Exports<"zipkin/lib/annotation">;
}
declare module "zipkin/lib/batch-recorder.js" {
  declare module.exports: $Exports<"zipkin/lib/batch-recorder">;
}
declare module "zipkin/lib/console-recorder.js" {
  declare module.exports: $Exports<"zipkin/lib/console-recorder">;
}
declare module "zipkin/lib/encoder.js" {
  declare module.exports: $Exports<"zipkin/lib/encoder">;
}
declare module "zipkin/lib/explicit-context.js" {
  declare module.exports: $Exports<"zipkin/lib/explicit-context">;
}
declare module "zipkin/lib/httpHeaders.js" {
  declare module.exports: $Exports<"zipkin/lib/httpHeaders">;
}
declare module "zipkin/lib/index.js" {
  declare module.exports: $Exports<"zipkin/lib/index">;
}
declare module "zipkin/lib/InetAddress.js" {
  declare module.exports: $Exports<"zipkin/lib/InetAddress">;
}
declare module "zipkin/lib/instrumentation/httpClient.js" {
  declare module.exports: $Exports<"zipkin/lib/instrumentation/httpClient">;
}
declare module "zipkin/lib/instrumentation/httpServer.js" {
  declare module.exports: $Exports<"zipkin/lib/instrumentation/httpServer">;
}
declare module "zipkin/lib/instrumentation/index.js" {
  declare module.exports: $Exports<"zipkin/lib/instrumentation/index">;
}
declare module "zipkin/lib/json-v1.js" {
  declare module.exports: $Exports<"zipkin/lib/json-v1">;
}
declare module "zipkin/lib/jsonEncoder.js" {
  declare module.exports: $Exports<"zipkin/lib/jsonEncoder">;
}
declare module "zipkin/lib/model.js" {
  declare module.exports: $Exports<"zipkin/lib/model">;
}
declare module "zipkin/lib/option.js" {
  declare module.exports: $Exports<"zipkin/lib/option">;
}
declare module "zipkin/lib/request.js" {
  declare module.exports: $Exports<"zipkin/lib/request">;
}
declare module "zipkin/lib/time.js" {
  declare module.exports: $Exports<"zipkin/lib/time">;
}
declare module "zipkin/lib/tracer/index.js" {
  declare module.exports: $Exports<"zipkin/lib/tracer/index">;
}
declare module "zipkin/lib/tracer/noop.js" {
  declare module.exports: $Exports<"zipkin/lib/tracer/noop">;
}
declare module "zipkin/lib/tracer/randomTraceId.js" {
  declare module.exports: $Exports<"zipkin/lib/tracer/randomTraceId">;
}
declare module "zipkin/lib/tracer/record.js" {
  declare module.exports: $Exports<"zipkin/lib/tracer/record">;
}
declare module "zipkin/lib/tracer/sampler.js" {
  declare module.exports: $Exports<"zipkin/lib/tracer/sampler">;
}
declare module "zipkin/lib/tracer/TraceId.js" {
  declare module.exports: $Exports<"zipkin/lib/tracer/TraceId">;
}
declare module "zipkin/src/annotation.js" {
  declare module.exports: $Exports<"zipkin/src/annotation">;
}
declare module "zipkin/src/batch-recorder.js" {
  declare module.exports: $Exports<"zipkin/src/batch-recorder">;
}
declare module "zipkin/src/console-recorder.js" {
  declare module.exports: $Exports<"zipkin/src/console-recorder">;
}
declare module "zipkin/src/explicit-context.js" {
  declare module.exports: $Exports<"zipkin/src/explicit-context">;
}
declare module "zipkin/src/httpHeaders.js" {
  declare module.exports: $Exports<"zipkin/src/httpHeaders">;
}
declare module "zipkin/src/index.js" {
  declare module.exports: $Exports<"zipkin/src/index">;
}
declare module "zipkin/src/InetAddress.js" {
  declare module.exports: $Exports<"zipkin/src/InetAddress">;
}
declare module "zipkin/src/instrumentation/httpClient.js" {
  declare module.exports: $Exports<"zipkin/src/instrumentation/httpClient">;
}
declare module "zipkin/src/instrumentation/httpServer.js" {
  declare module.exports: $Exports<"zipkin/src/instrumentation/httpServer">;
}
declare module "zipkin/src/instrumentation/index.js" {
  declare module.exports: $Exports<"zipkin/src/instrumentation/index">;
}
declare module "zipkin/src/jsonEncoder.js" {
  declare module.exports: $Exports<"zipkin/src/jsonEncoder">;
}
declare module "zipkin/src/model.js" {
  declare module.exports: $Exports<"zipkin/src/model">;
}
declare module "zipkin/src/option.js" {
  declare module.exports: $Exports<"zipkin/src/option">;
}
declare module "zipkin/src/request.js" {
  declare module.exports: $Exports<"zipkin/src/request">;
}
declare module "zipkin/src/time.js" {
  declare module.exports: $Exports<"zipkin/src/time">;
}
declare module "zipkin/src/tracer/index.js" {
  declare module.exports: $Exports<"zipkin/src/tracer/index">;
}
declare module "zipkin/src/tracer/noop.js" {
  declare module.exports: $Exports<"zipkin/src/tracer/noop">;
}
declare module "zipkin/src/tracer/randomTraceId.js" {
  declare module.exports: $Exports<"zipkin/src/tracer/randomTraceId">;
}
declare module "zipkin/src/tracer/record.js" {
  declare module.exports: $Exports<"zipkin/src/tracer/record">;
}
declare module "zipkin/src/tracer/sampler.js" {
  declare module.exports: $Exports<"zipkin/src/tracer/sampler">;
}
declare module "zipkin/src/tracer/TraceId.js" {
  declare module.exports: $Exports<"zipkin/src/tracer/TraceId">;
}
declare module "zipkin/test/annotation.test.js" {
  declare module.exports: $Exports<"zipkin/test/annotation.test">;
}
declare module "zipkin/test/batch-recorder.test.js" {
  declare module.exports: $Exports<"zipkin/test/batch-recorder.test">;
}
declare module "zipkin/test/explicit-context.test.js" {
  declare module.exports: $Exports<"zipkin/test/explicit-context.test">;
}
declare module "zipkin/test/httpClientInstrumentation.test.js" {
  declare module.exports: $Exports<
    "zipkin/test/httpClientInstrumentation.test"
  >;
}
declare module "zipkin/test/httpServerInstrumentation.test.js" {
  declare module.exports: $Exports<
    "zipkin/test/httpServerInstrumentation.test"
  >;
}
declare module "zipkin/test/InetAddress.test.js" {
  declare module.exports: $Exports<"zipkin/test/InetAddress.test">;
}
declare module "zipkin/test/jsonEncoder.JSON_V1.test.js" {
  declare module.exports: $Exports<"zipkin/test/jsonEncoder.JSON_V1.test">;
}
declare module "zipkin/test/jsonEncoder.JSON_V2.test.js" {
  declare module.exports: $Exports<"zipkin/test/jsonEncoder.JSON_V2.test">;
}
declare module "zipkin/test/model.test.js" {
  declare module.exports: $Exports<"zipkin/test/model.test">;
}
declare module "zipkin/test/randomTraceId.test.js" {
  declare module.exports: $Exports<"zipkin/test/randomTraceId.test">;
}
declare module "zipkin/test/request.test.js" {
  declare module.exports: $Exports<"zipkin/test/request.test">;
}
declare module "zipkin/test/sampler.test.js" {
  declare module.exports: $Exports<"zipkin/test/sampler.test">;
}
declare module "zipkin/test/trace.test.js" {
  declare module.exports: $Exports<"zipkin/test/trace.test">;
}
declare module "zipkin/test/TraceId.test.js" {
  declare module.exports: $Exports<"zipkin/test/TraceId.test">;
}
