// flow-typed signature: 404c88f2dbb3e585b6132198805d4287
// flow-typed version: <<STUB>>/zipkin-javascript-opentracing_v^1.4.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zipkin-javascript-opentracing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

interface Span {
  log({ [string]: string }): void;
  finish(): void;
}

type startSpanOptions = {
  childOf?: ?Object
};

interface TracerType {
  startSpan(spanName: string, options?: ?startSpanOptions): Span;
  inject(span: Span, format: string, headers: Object): void;
}

declare module "zipkin-javascript-opentracing" {
  declare module.exports: Object => TracerType;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "zipkin-javascript-opentracing/__mocks__/zipkin-option" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/__mocks__/zipkin" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/integration/basic_spec" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/support/commands" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/support/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/utils/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/src/App" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/src/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/src/screens/Basic" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/e2e-tests/react/src/screens/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/example/advanced/client" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/example/advanced/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/example/advanced/server" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/example/basic/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/example/recorder" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/lib/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/src/__tests__/e2e" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/src/__tests__/index" {
  declare module.exports: any;
}

declare module "zipkin-javascript-opentracing/src/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "zipkin-javascript-opentracing/__mocks__/zipkin-option.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/__mocks__/zipkin-option"
  >;
}
declare module "zipkin-javascript-opentracing/__mocks__/zipkin.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/__mocks__/zipkin"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/integration/basic_spec.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/cypress/integration/basic_spec"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/support/commands.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/cypress/support/commands"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/support/index.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/cypress/support/index"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/cypress/utils/index.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/cypress/utils/index"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/src/App.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/src/App"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/src/index.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/src/index"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/src/screens/Basic.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/src/screens/Basic"
  >;
}
declare module "zipkin-javascript-opentracing/e2e-tests/react/src/screens/index.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/e2e-tests/react/src/screens/index"
  >;
}
declare module "zipkin-javascript-opentracing/example/advanced/client.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/example/advanced/client"
  >;
}
declare module "zipkin-javascript-opentracing/example/advanced/index.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/example/advanced/index"
  >;
}
declare module "zipkin-javascript-opentracing/example/advanced/server.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/example/advanced/server"
  >;
}
declare module "zipkin-javascript-opentracing/example/basic/index.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/example/basic/index"
  >;
}
declare module "zipkin-javascript-opentracing/example/recorder.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/example/recorder"
  >;
}
declare module "zipkin-javascript-opentracing/lib/index.js" {
  declare module.exports: $Exports<"zipkin-javascript-opentracing/lib/index">;
}
declare module "zipkin-javascript-opentracing/src/__tests__/e2e.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/src/__tests__/e2e"
  >;
}
declare module "zipkin-javascript-opentracing/src/__tests__/index.js" {
  declare module.exports: $Exports<
    "zipkin-javascript-opentracing/src/__tests__/index"
  >;
}
declare module "zipkin-javascript-opentracing/src/index.js" {
  declare module.exports: $Exports<"zipkin-javascript-opentracing/src/index">;
}
